# Generated by Django 3.1.7 on 2021-03-22 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_group_slug'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_object_following',
        ),
    ]
